spring:    
  datasource:
    url: jdbc:postgresql://localhost:5432/llmtopdfintegration
    username: postgres
    password: easypwd
  jpa:
    properties:
       hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
       ddl-auto: update
